site_name: Initiatehub Documentation

nav:
        - Home: index.md
        - Flutter:
                  - Project Structure: flutter/project-structure.md
                  - New Project with Firebase: flutter/new-project-with-firebase.md
        - Strapi:
                  - Deploy Guide: strapi/strapi-deploy-guide.md
        - Projects:
                  - Encyclopedia:
                            - Overview: projects/encyclopedia/index.md
                            - Features Wall: projects/encyclopedia/features-wall.md

theme:
        name: material
        features:
                - navigation.tabs
                - navigation.sections
