site_name: Initiatehub Documentation

nav:
  - Home: index.md
  - Projects:
      - Website 1:
          - Overview: projects/website1/index.md
          - Setup: projects/website1/setup.md
          - Deployment: projects/website1/deployment.md
      - Website 2:
          - Overview: projects/website2/index.md
          - Setup: projects/website2/setup.md
          - Deployment: projects/website2/deployment.md
      - Mobile App 1:
          - Overview: projects/mobile-app1/index.md
          - Setup: projects/mobile-app1/setup.md
          - Deployment: projects/mobile-app1/deployment.md
      - Mobile App 2:
          - Overview: projects/mobile-app2/index.md
          - Setup: projects/mobile-app2/setup.md
          - Deployment: projects/mobile-app2/deployment.md
  - Processes:
      - General:
          - Setting Up Flutter: processes/general/setup-flutter.md
          - Authentication: processes/general/authentication.md
          - Testing: processes/general/testing.md
      - Development:
          - Code Standards: processes/development/code-standards.md
          - Version Control: processes/development/version-control.md
          - CI/CD: processes/development/ci-cd.md
  - About: about.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
