site_name: Initiatehub Documentation

nav:
    - Home: index.md
    - Processes:
          - New Flutter Project with Firebase: processes/firebase-flutter.md

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
