site_name: Initiatehub
nav:
        - Home: index.md
        - Projects:
                  - Encyclopedia:
                            - Overview: projects/encyclopedia/index.md
                            - Features Wall: projects/encyclopedia/features-wall.md
                            - Categories & Topics: projects/encyclopedia/categories-and-topics.md
                            - Content Models: projects/encyclopedia/content_models_strapi.md
        - Flutter:
                  - Project Structure: flutter/project-structure.md
                  - New Project with Firebase: flutter/new-project-with-firebase.md
        - Server:
                  - Secure VPS Server: server/secure_vps.md
                  - Nginx Setup: server/nginx.md
        - Strapi:
                  - Deploy Guide: strapi/strapi-deploy-guide.md

theme:
        name: material
        palette:
                primary: "teal" # Set the primary color to red

        highlightjs: true
        hljs_languages:
                - yaml
                - Dockerfile
                - bash

markdown_extensions:
        - codehilite:
                  guess_lang: false # Prevents automatic guessing of language, rely on specified language
                  linenums: true # Optional: adds line numbers to code blocks
        - pymdownx.superfences # Enhances code block handling
