site_name: Initiatehub Documentation

nav:
    - Home: index.md
    - About: about.md
    - Processes:
          - General:
                - Setting Up Flutter: processes/general/setup-flutter.md
                - Authentication: processes/general/authentication.md
                - Testing: processes/general/testing.md
          - Development:
                - Code Standards: processes/development/code-standards.md
                - Version Control: processes/development/version-control.md
                - CI/CD: processes/development/ci-cd.md

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
