site_name: Initiatehub Documentation

nav:
    - Home: index.md
    - Processes:
          - New Flutter Project with Firebase: processes/firebase-flutter.md
    - Projects:
          - Encyclopedia:
                - Overview: projects/encyclopedia/index.md
                - Features Wall: projects/encyclopedia/features-wall.md

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
